# Generated by Django 3.1.7 on 2021-06-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=100, verbose_name='Giới tính')),
                ('age', models.IntegerField(verbose_name='Tuổi')),
                ('organization', models.CharField(max_length=100, verbose_name='Tổ chức')),
            ],
            options={
                'verbose_name': 'Tác giả',
                'verbose_name_plural': 'Tác giả',
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_off', models.FloatField(verbose_name='Khuyến mãi')),
                ('price', models.FloatField(verbose_name='Giá bán')),
            ],
            options={
                'verbose_name': 'Sản phẩm đang bán',
                'verbose_name_plural': 'Sản phẩm đang bán',
            },
        ),
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nhà sản xuất',
                'verbose_name_plural': 'Nhà sản xuất',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
            ],
            options={
                'verbose_name': 'Nhà sản xuất',
                'verbose_name_plural': 'Nhà sản xuất',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('price', models.FloatField(verbose_name='Giá mua')),
                ('image', models.ImageField(upload_to='', verbose_name='Ảnh')),
                ('type', models.IntegerField()),
                ('status', models.CharField(choices=[('True', 'Đang Kinh Doanh'), ('False', 'Ngừng Kinh Doanh')], default=True, max_length=10, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('material', models.CharField(max_length=100, verbose_name='Chất')),
                ('desc', models.CharField(max_length=100, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Quần áo',
                'verbose_name_plural': 'Quần áo',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('desc', models.CharField(max_length=100, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Đồ điện tử',
                'verbose_name_plural': 'Đồ điện tử',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='ProductInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='Lượng tồn kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Nhập kho sản phẩm',
                'verbose_name_plural': 'Nhập kho sản phẩm',
            },
        ),
    ]
