# Generated by Django 3.1.7 on 2021-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=100, verbose_name='Địa chỉ chi tiết')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('country', models.CharField(max_length=100, verbose_name='Đất nước')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Tên')),
                ('lastname', models.CharField(max_length=100, verbose_name='Họ và tên đệm')),
            ],
            options={
                'verbose_name': 'Họ và tên',
                'verbose_name_plural': 'Họ và tên',
            },
        ),
    ]
