# Generated by Django 3.1.7 on 2021-06-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('staff', '0002_staff_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatuslogs',
            name='business_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Nhân viên kinh doanh'),
        ),
        migrations.AddField(
            model_name='orderstatuslogs',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='orderstatuslogs',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus', verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AddField(
            model_name='orderstatuslogs',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shipment', verbose_name='Giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.payment', verbose_name='Thanh toán'),
        ),
        migrations.AddField(
            model_name='notification',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shipment'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='credit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.creditcard'),
        ),
    ]
